const fs = require('fs');

const supabaseUrl = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || '';
const supabaseAnonKey = process.env.VITE_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY || '';

const content = `// Auto-generated by Vercel Build Step
window.SUPABASE_URL = "${supabaseUrl}";
window.SUPABASE_ANON_KEY = "${supabaseAnonKey}";
`;

fs.writeFileSync('env.js', content);
console.log('✅ Generated env.js from Vercel Environment Variables');
